

import java.awt.Graphics;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANEES ALAM
 */
public final class QuizMain extends javax.swing.JFrame {

    /**
     * Creates new form QuizMain
     */
    String qno[][]=new String[5][5];
    String rightans[][]=new String[5][2];
    String userans[]=new String[5];
    
    
    public static int timer=30;
    public static int counter=0;
    public boolean agiven=false;
    public QuizMain() {
        initComponents();
        btnsubmit.setEnabled(false);
        //Question Framing
qno[0][0]="Who is the father of Java ?";
qno[0][1]="James Gosling";
qno[0][2]="Peter Naugton";
qno[0][3]="Mike Sherdon";
qno[0][4]="John";

qno[1][0]="How many primitive data types are there  ?";
qno[1][1]="8";
qno[1][2]="4";
qno[1][3]="3";
qno[1][4]="1";

qno[2][0]="All Wrapper clases are present in which package";
qno[2][1]="java.util";
qno[2][2]="java.io";
qno[2][3]="java.lang";
qno[2][4]="java.awt";

qno[3][0]="Super class of all the classes ?";
qno[3][1]="Class";
qno[3][2]="Object";
qno[3][3]="System";
qno[3][4]="Math";

qno[4][0]="Thread.sleep( ) raise which exception ?";
qno[4][1]="IOException";
qno[4][2]="SQLException";
qno[4][3]="InterruptedException";
qno[4][4]="ArrayIndexOutOfBoundException";

//Answer Feeding
rightans[0][0]="1";
rightans[0][1]="James Gosling";
rightans[1][0]="2";
rightans[1][1]="8";
rightans[2][0]="3";
rightans[2][1]="java.lang";
rightans[3][0]="4";
rightans[3][1]="Object";
rightans[4][0]="5";
rightans[4][1]="InterruptedException";

        

RadioGroup.add(op1);
RadioGroup.add(op2);
RadioGroup.add(op3);
RadioGroup.add(op4);
QuestionFeed(counter);

    }
    @Override
    public void paint(Graphics G)
    {
        super.paint(G);
        String result="Time Remaining "+timer+" Seconds";
        lbltimer.setText(result);
        
        if(timer>0)
        {
            lbltimer.setText(result);
        }
        else
        {
            result="Time Up!!";
            lbltimer.setText(result);
            //Thread.sleep(1000);
            if(counter==4)
            {
            JOptionPane.showMessageDialog(this,"Exam Time is Over..");                btnsubmit.setEnabled(true);
            if(RadioGroup.getSelection()==null)
            {
                userans[counter]="";
                
            }
            else
            {
                userans[counter]=RadioGroup.getSelection().getActionCommand();
            }
            //this.setVisible(false);
            //ScoreFrame obj=new ScoreFrame();
            //obj.setVisible(true);
            closing();
            return;                
                            
            }
            //code
            
            //code
    
        }
        timer--;
        try
        {
            Thread.sleep(1000);
            repaint();

        }
        catch(Exception e)
        {
            
        }
        
        if(agiven==true)
        {
            agiven=false;
            timer=30;
            if(RadioGroup.getSelection()==null)
            {
                userans[counter]="";
                
            }
            else
            {
                userans[counter]=RadioGroup.getSelection().getActionCommand();
            }
            if(counter==3)
            {
                btnNext.setEnabled(false);
                btnsubmit.setEnabled(true);
            }
            
            counter++;
            QuestionFeed(counter);
        }
         else if(timer<0)
        {
            timer=30;
            if(RadioGroup.getSelection()==null)
            {
                userans[counter]="";
                
            }
            else
            {
                userans[counter]=RadioGroup.getSelection().getActionCommand();
            }
            counter++;
            QuestionFeed(counter);
        }
    }
    
    public  void QuestionFeed(int c)
    {
       lblQuestionNo.setText(""+(c+1));
       lblQuestion.setText(""+qno[c][0]);
       op1.setText(""+qno[c][1]);
       op1.setActionCommand(qno[c][1]);
       op2.setText(""+qno[c][2]);
       op2.setActionCommand(qno[c][2]);
       op3.setText(""+qno[c][3]);
       op3.setActionCommand(qno[c][3]);
       op4.setText(""+qno[c][4]);
       op4.setActionCommand(qno[c][4]);
       RadioGroup.clearSelection();  //To clear the mark radiobutton
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        op2 = new javax.swing.JRadioButton();
        op1 = new javax.swing.JRadioButton();
        lblQuestionNo = new javax.swing.JLabel();
        op3 = new javax.swing.JRadioButton();
        op4 = new javax.swing.JRadioButton();
        lblQuestion = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnsubmit = new javax.swing.JButton();
        lbltimer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Online Examination ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(jLabel1)
                .addContainerGap(475, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        op2.setBackground(new java.awt.Color(204, 255, 255));
        op2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        op2.setForeground(new java.awt.Color(0, 0, 102));
        op2.setText("jRadioButton1");

        op1.setBackground(new java.awt.Color(204, 255, 255));
        op1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        op1.setForeground(new java.awt.Color(0, 0, 102));
        op1.setText("jRadioButton1");

        lblQuestionNo.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        lblQuestionNo.setText("1");

        op3.setBackground(new java.awt.Color(204, 255, 255));
        op3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        op3.setForeground(new java.awt.Color(0, 0, 102));
        op3.setText("jRadioButton1");

        op4.setBackground(new java.awt.Color(204, 255, 255));
        op4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        op4.setForeground(new java.awt.Color(0, 0, 102));
        op4.setText("jRadioButton1");

        lblQuestion.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        lblQuestion.setText("Question Will be Frame Here");

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnsubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnsubmit)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuestionNo)
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(op4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(op3)
                            .addComponent(op1)
                            .addComponent(lblQuestion)
                            .addComponent(op2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuestionNo)
                            .addComponent(lblQuestion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(op1)
                        .addGap(27, 27, 27)
                        .addComponent(op3)
                        .addGap(27, 27, 27)
                        .addComponent(op2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(op4)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        lbltimer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbltimer, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbltimer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1132, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
       agiven=true;
       repaint();
       //counter++;
       //QuestionFeed(counter);
    }//GEN-LAST:event_btnNextActionPerformed
    public void closing()
    {
        int i,notattempted=0,tot=0,attempted=0,tq=5,wrong=0;
        String ans="";
        
        if(RadioGroup.getSelection()==null)
            {
                userans[counter]="";
                
            }
            else
            {
                userans[counter]=RadioGroup.getSelection().getActionCommand();
            }
        String x="";    
        for(i=0;i<=4;i++)
        {
            ans+=userans[i]+" ";
            x+=rightans[i][1]+" ";
        }
        System.out.println("Result Ans "+ans);
        System.out.println("Main Ans   "+x);
        //this.setVisible(false );
        for(i=0;i<=4;i++)
        {
            if(rightans[i][1].equals(userans[i]))
            {
                tot+=10;
            }
            else if(userans[i].equals(""))
            {
                notattempted++;
            }
            else
            {
                wrong++;
                tot-=5;
            }
        }
        attempted=tq-notattempted;
        Score.total=tot;
        Score.missQ=notattempted;
        Score.numberofquestion=tq; 
        Score.attemptQ=attempted;
        Score.wrongans=wrong;
        if(tot<30)
        {
            Score.status="Not Qualified";
        }
                
        //JOptionPane.showMessageDialog(this,tq+" "+attempted+" "+notattempted+" "+tot);
        this.setVisible(false);
        ScoreFrame obj = new ScoreFrame();
        obj.setVisible(true);
    }
    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        //Submit Button Coding
        closing();
    }//GEN-LAST:event_btnsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
             
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizMain().setVisible(true);
            }
        });
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup RadioGroup;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblQuestionNo;
    private javax.swing.JLabel lbltimer;
    private javax.swing.JRadioButton op1;
    private javax.swing.JRadioButton op2;
    private javax.swing.JRadioButton op3;
    private javax.swing.JRadioButton op4;
    // End of variables declaration//GEN-END:variables
}
