

import java.awt.Graphics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ANEES ALAM
 */
public class OnlineExam extends javax.swing.JFrame {

    /**
     * Creates new form OnlineExam
     */
    String qno[][]=new String[5][5];
    String rightans[][]=new String[5][2];
    String userans[][]=new String[5][1];
    
    
    public static int timer=10;
    public static int counter=0;
    public boolean agiven=false;
    public OnlineExam() {
        initComponents();
        QuestionSet();
        btnsubmit.setEnabled(false);
        QuestionFeed(counter);
    }
    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
        String result="Time Remaining "+timer+" Seconds";
        lbltimer.setText(result);
        
        if(timer>0)
        {
            lbltimer.setText(result);
        }
        else
        {
            result="Time Up!!";
            lbltimer.setText(result);
            //Thread.sleep(1000);
            if(counter==4)
               return;
        }
        timer--;
        try
        {
            Thread.sleep(1000);
            repaint();

        }
        catch(Exception e)
        {
            
        }
    }
    public void QuestionSet()
    {
        qno[0][0]="Who is the father of Java ?";
        qno[0][1]="James Gosling";
        qno[0][2]="Peter Naugton";
        qno[0][3]="Mike Sherdon";
        qno[0][4]="John";

        qno[1][0]="How many primitive data types are there  ?";
        qno[1][1]="8";
        qno[1][2]="4";
        qno[1][3]="3";
        qno[1][4]="1";

        qno[2][0]="All Wrapper clases are present in which package";
        qno[2][1]="java.util";
        qno[2][2]="java.io";
        qno[2][3]="java.lang";
        qno[2][4]="java.awt";

        qno[3][0]="Super class of all the classes ?";
        qno[3][1]="Class";
        qno[3][2]="Object";
        qno[3][3]="System";
        qno[3][4]="Math";

        qno[4][0]="Thread.sleep( ) raise which exception ?";
        qno[4][1]="Class";
        qno[4][2]="Object";
        qno[4][3]="System";
        qno[4][4]="Math";
    }
    public  void QuestionFeed(int c)
    {
       lblQuestionNo.setText(""+(c+1));
       lblQuestion.setText(""+qno[c][0]);
       op1.setText(""+qno[c][1]);
       op1.setActionCommand(qno[c][1]);
       op2.setText(""+qno[c][2]);
       op2.setActionCommand(qno[c][2]);
       op3.setText(""+qno[c][3]);
       op3.setActionCommand(qno[c][3]);
       op4.setText(""+qno[c][4]);
       op3.setActionCommand(qno[c][4]);
       RadioGroup.clearSelection();  //To clear the mark radiobutton
       
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioGroup = new javax.swing.ButtonGroup();
        lblQuestionNo = new javax.swing.JLabel();
        op2 = new javax.swing.JRadioButton();
        lblQuestion = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        bntnext = new javax.swing.JButton();
        op3 = new javax.swing.JRadioButton();
        op4 = new javax.swing.JRadioButton();
        op1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbltimer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 153));

        lblQuestionNo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblQuestionNo.setText("jLabel1");

        RadioGroup.add(op2);
        op2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        op2.setForeground(new java.awt.Color(0, 0, 153));
        op2.setText("jRadioButton1");

        lblQuestion.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblQuestion.setText("jLabel1");

        btnsubmit.setText("Submit");

        bntnext.setText("Next");

        RadioGroup.add(op3);
        op3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        op3.setForeground(new java.awt.Color(0, 0, 153));
        op3.setText("jRadioButton1");

        RadioGroup.add(op4);
        op4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        op4.setForeground(new java.awt.Color(0, 0, 153));
        op4.setText("jRadioButton1");

        RadioGroup.add(op1);
        op1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        op1.setForeground(new java.awt.Color(0, 0, 153));
        op1.setText("jRadioButton1");

        jLabel1.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel1.setText("Online Examination ");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 51));

        lbltimer.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(op4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblQuestionNo)
                        .addGap(53, 53, 53)
                        .addComponent(lblQuestion)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(op1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(op3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(op2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntnext, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(377, 377, 377))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(lbltimer)
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbltimer))
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuestionNo)
                    .addComponent(lblQuestion))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(op1)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addComponent(op2)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op3)
                    .addComponent(bntnext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(op4)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OnlineExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OnlineExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OnlineExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OnlineExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OnlineExam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup RadioGroup;
    private javax.swing.JButton bntnext;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblQuestionNo;
    private javax.swing.JLabel lbltimer;
    private javax.swing.JRadioButton op1;
    private javax.swing.JRadioButton op2;
    private javax.swing.JRadioButton op3;
    private javax.swing.JRadioButton op4;
    // End of variables declaration//GEN-END:variables
}
